# Generated by Django 6.0.1 on 2026-01-20 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 20, 18, 37, 17, 598166, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
