# Generated by Django 6.0.1 on 2026-01-20 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_document_active_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
