# Generated by Django 6.0.1 on 2026-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_alter_document_active_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(null=True),
        ),
    ]
